server:
  port: 8083
  
spring:
  application:
    name: dubbo-demo-rmb-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rpc02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#    druid:
#      url: jdbc:mysql://localhost:3306/rpc02?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: 123456

dubbo:
  scan:
    base-packages: io.kimmking.dubbo.demo.rmbprovider
  protocol:
    name: dubbo
    port: 12346
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
#  application:
#    qosEnable: true
#    qosPort: 22222
#    qosAcceptForeignIp: true
#    qos-enable-compatible: true
#    qos-host-compatible: localhost
#    qos-port-compatible: 22222
#    qos-accept-foreign-ip-compatible: true
#    qos-host: localhost